apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "front.fullname" . }}
  labels:
    app: {{ template "front.name" . }}
    chart: {{ template "front.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "front.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "front.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: {{ template "front.fullname" . }}-nginx-config
      containers:
        # nginx web server
        - name: nginx
          image: nginx:1.15-alpine
          ports:
          - name: http
            containerPort: 80
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.envs | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{ if .Values.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: http
            initialDelaySeconds: 5
            perdiodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
{{ end }}
{{ if .Values.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: http
            initialDelaySeconds: 5
            perdiodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
